### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by gukii** [jherr/qwik-voting#1]
I know this repo is a companion to your excellent youtube content of which I m totally appreciative.

It would be super convenient and great for DX to have the installation instructions for this repo. 

It just takes time to go thru the whole video again and following step by step. 

I got tripped up by this:
- git clone of the reo..
- pnpm install
- pnpm prisma migrate reset (which throws)
- npm start

left me with a with some kind of vite error, which is probably my fault somewhere..

error: "There was a problem with the server configuration. Check the server logs for more information."

```
There was a problem with the server configuration. Check the server logs for more information.
    at getSessionData (/home/santa/code/qwik/qwik-voting/node_modules/.pnpm/@builder.io+qwik-auth@0.1.0_@auth+core@0.7.1_@builder.io+qwik-city@1.0.0_@builder.io+qwik@1.0.0/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:310:8)
    at async onRequest (/home/santa/code/qwik/qwik-voting/node_modules/.pnpm/@builder.io+qwik-auth@0.1.0_@auth+core@0.7.1_@builder.io+qwik-city@1.0.0_@builder.io+qwik@1.0.0/node_modules/@builder.io/qwik-auth/lib/index.qwik.mjs:281:37)
    at async Object.next (/home/santa/code/qwik/qwik-voting/node_modules/.pnpm/@builder.io+qwik-city@1.0.0/node_modules/@builder.io/qwik-city/vite/index.cjs:24103:9)
    at async runNext (/home/santa/code/qwik/qwik-voting/node_modules/.pnpm/@builder.io+qwik-city@1.0.0/node_modules/@builder.io/qwik-city/vite/index.cjs:24336:5)
    at async /home/santa/code/qwik/qwik-voting/node_modules/.pnpm/@builder.io+qwik-city@1.0.0/node_modules/@builder.io/qwik-city/vite/index.cjs:24746:26
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

**Comment by brandiqa** [comment]
You'll need to copy `env.example` to `.env` and populate the secret fields before you execute `npm start`. 

An updated readme with the proper instructions would be nice.
